### ISSUE TITLE
code

### ISSUE THREAD

**Issue by lGrandRevelation** [stormdirus2/the_architect#1]
Im trying to make an origin with a ghast fireball attack that costs 3 levels. any idea of what the code should look like?

**Comment by stormdirus2** [comment]
![CodeExample](https://user-images.githubusercontent.com/78043489/117147023-11b6c600-ad72-11eb-807e-f4a2d3649f24.png)

**Comment by stormdirus2** [comment]
In all honesty, this is quite possible through datapacks.
I suggest getting help on the Origins discord, rather than bugging some random dude in their Github Issues,
It isn't made for this.
