### ISSUE TITLE
Ideea: Make it so that if you double press g with architect's focus on your left hand or right hand you jump 5blocks in the air allowing you to gain height without needing to jump!

### ISSUE THREAD

**Issue by Vlad2314243** [stormdirus2/the_architect#4]

**Comment by stormdirus2** [comment]
This would make it hard to use the Spatial Stride while holding the architect's focus. Additionally, the whole balance of the spatial stride is to _keep_ people from climbing altitude without using something to jump off of. Its more about walking on air, not soaring through the sky.
